trigger:
  - main

pool:
  name: Linux_Agent

variables:
  NODE_VERSION: '18.17.1'

steps:
  - task: UseNode@1
    inputs:
      version: '$(NODE_VERSION)'
    displayName: 'Use Node.js $(NODE_VERSION)'

  - script: |
      npm install
    workingDirectory: 'app'
    displayName: 'Install dependencies'

  # - script: |
  #     npm test
  #   workingDirectory: 'app'
  #   displayName: 'Run tests'

  - script: |
      npm run build
    workingDirectory: 'app'
    displayName: 'Build app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
