name: Dependency Vulnerability Check

on:
  workflow_dispatch:

jobs:
  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: Linux_runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for Node.js project
        id: check_node
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Node.js project detected."
            echo "is_node=true" >> $GITHUB_OUTPUT
          else
            echo "No Node.js project found."
            echo "is_node=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.check_node.outputs.is_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run npm audit
        if: steps.check_node.outputs.is_node == 'true'
        run: |
          npm install --production
          npm audit --production
